"""Declarative visual-config field specifications for the admin UI."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ConfigFieldSpec:
    """Renderable visual-config field."""

    name: str
    path: tuple[str, ...]
    kind: str
    label_key: str
    hint_key: str | None = None
    options: tuple[str, ...] = ()
    rows: int = 4
    placeholder: str = ""
    restart_required: bool = False


_CONFIG_FIELDS = (
    ConfigFieldSpec(
        "agents_defaults_workspace",
        ("agents", "defaults", "workspace"),
        "text",
        "admin_config_agents_workspace_label",
        "admin_config_agents_workspace_hint",
        placeholder="",
    ),
    ConfigFieldSpec(
        "agents_defaults_model",
        ("agents", "defaults", "model"),
        "text",
        "admin_config_agents_model_label",
        placeholder="openrouter/openai/gpt-4o-mini",
    ),
    ConfigFieldSpec(
        "agents_defaults_provider",
        ("agents", "defaults", "provider"),
        "text",
        "admin_config_agents_provider_label",
        "admin_config_agents_provider_hint",
        placeholder="auto",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "agents_defaults_provider_pool_strategy",
        ("agents", "defaults", "providerPool", "strategy"),
        "select",
        "admin_config_agents_provider_pool_strategy_label",
        "admin_config_agents_provider_pool_strategy_hint",
        options=("failover", "round_robin"),
        restart_required=True,
    ),
    ConfigFieldSpec(
        "agents_defaults_provider_pool_targets",
        ("agents", "defaults", "providerPool", "targets"),
        "provider_pool_targets",
        "admin_config_agents_provider_pool_targets_label",
        "admin_config_agents_provider_pool_targets_hint",
        rows=8,
        restart_required=True,
    ),
    ConfigFieldSpec(
        "agents_defaults_max_tokens",
        ("agents", "defaults", "maxTokens"),
        "int",
        "admin_config_agents_max_tokens_label",
    ),
    ConfigFieldSpec(
        "agents_defaults_context_window_tokens",
        ("agents", "defaults", "contextWindowTokens"),
        "int",
        "admin_config_agents_context_window_label",
    ),
    ConfigFieldSpec(
        "agents_defaults_temperature",
        ("agents", "defaults", "temperature"),
        "float",
        "admin_config_agents_temperature_label",
    ),
    ConfigFieldSpec(
        "agents_defaults_max_tool_iterations",
        ("agents", "defaults", "maxToolIterations"),
        "int",
        "admin_config_agents_max_tool_iterations_label",
    ),
    ConfigFieldSpec(
        "agents_defaults_tool_hint_max_length",
        ("agents", "defaults", "toolHintMaxLength"),
        "int",
        "admin_config_agents_tool_hint_max_length_label",
    ),
    ConfigFieldSpec(
        "agents_defaults_reasoning_effort",
        ("agents", "defaults", "reasoningEffort"),
        "select",
        "admin_config_agents_reasoning_effort_label",
        options=("", "low", "medium", "high"),
    ),
    ConfigFieldSpec(
        "agents_defaults_timezone",
        ("agents", "defaults", "timezone"),
        "text",
        "admin_config_agents_timezone_label",
        placeholder="Asia/Shanghai",
    ),
    ConfigFieldSpec(
        "providers_openrouter_api_key",
        ("providers", "openrouter", "apiKey"),
        "text",
        "admin_config_providers_openrouter_api_key_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "providers_openrouter_api_base",
        ("providers", "openrouter", "apiBase"),
        "text",
        "admin_config_providers_openrouter_api_base_label",
        placeholder="https://openrouter.ai/api/v1",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "providers_openai_api_key",
        ("providers", "openai", "apiKey"),
        "text",
        "admin_config_providers_openai_api_key_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "providers_openai_api_base",
        ("providers", "openai", "apiBase"),
        "text",
        "admin_config_providers_openai_api_base_label",
        placeholder="https://api.openai.com/v1",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "providers_anthropic_api_key",
        ("providers", "anthropic", "apiKey"),
        "text",
        "admin_config_providers_anthropic_api_key_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "providers_anthropic_api_base",
        ("providers", "anthropic", "apiBase"),
        "text",
        "admin_config_providers_anthropic_api_base_label",
        placeholder="https://api.anthropic.com",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "providers_deepseek_api_key",
        ("providers", "deepseek", "apiKey"),
        "text",
        "admin_config_providers_deepseek_api_key_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "providers_deepseek_api_base",
        ("providers", "deepseek", "apiBase"),
        "text",
        "admin_config_providers_deepseek_api_base_label",
        placeholder="https://api.deepseek.com",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "providers_custom_api_key",
        ("providers", "custom", "apiKey"),
        "text",
        "admin_config_providers_custom_api_key_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "providers_custom_api_base",
        ("providers", "custom", "apiBase"),
        "text",
        "admin_config_providers_custom_api_base_label",
        placeholder="https://api.your-provider.com/v1",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "providers_custom_extra_headers",
        ("providers", "custom", "extraHeaders"),
        "json",
        "admin_config_providers_custom_extra_headers_label",
        rows=5,
        restart_required=True,
    ),
    ConfigFieldSpec(
        "providers_ollama_api_base",
        ("providers", "ollama", "apiBase"),
        "text",
        "admin_config_providers_ollama_api_base_label",
        placeholder="http://localhost:11434/v1",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "providers_vllm_api_base",
        ("providers", "vllm", "apiBase"),
        "text",
        "admin_config_providers_vllm_api_base_label",
        placeholder="http://localhost:8000",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "gateway_host",
        ("gateway", "host"),
        "text",
        "admin_config_gateway_host_label",
        placeholder="0.0.0.0",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "gateway_port",
        ("gateway", "port"),
        "int",
        "admin_config_gateway_port_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "gateway_heartbeat_enabled",
        ("gateway", "heartbeat", "enabled"),
        "bool",
        "admin_config_gateway_heartbeat_enabled_label",
    ),
    ConfigFieldSpec(
        "gateway_heartbeat_interval_s",
        ("gateway", "heartbeat", "intervalS"),
        "int",
        "admin_config_gateway_heartbeat_interval_label",
    ),
    ConfigFieldSpec(
        "gateway_heartbeat_keep_recent_messages",
        ("gateway", "heartbeat", "keepRecentMessages"),
        "int",
        "admin_config_gateway_heartbeat_keep_recent_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "gateway_cron_max_sleep_ms",
        ("gateway", "cron", "maxSleepMs"),
        "int",
        "admin_config_gateway_cron_max_sleep_label",
    ),
    ConfigFieldSpec(
        "gateway_admin_enabled",
        ("gateway", "admin", "enabled"),
        "bool",
        "admin_config_gateway_admin_enabled_label",
    ),
    ConfigFieldSpec(
        "gateway_admin_auth_key",
        ("gateway", "admin", "authKey"),
        "text",
        "admin_config_gateway_admin_auth_key_label",
    ),
    ConfigFieldSpec(
        "gateway_status_enabled",
        ("gateway", "status", "enabled"),
        "bool",
        "admin_config_gateway_status_enabled_label",
    ),
    ConfigFieldSpec(
        "gateway_status_auth_key",
        ("gateway", "status", "authKey"),
        "text",
        "admin_config_gateway_status_auth_key_label",
        "admin_config_gateway_status_auth_key_hint",
    ),
    ConfigFieldSpec(
        "gateway_status_push_enabled",
        ("gateway", "status", "push", "enabled"),
        "bool",
        "admin_config_gateway_status_push_enabled_label",
    ),
    ConfigFieldSpec(
        "gateway_status_push_mode",
        ("gateway", "status", "push", "mode"),
        "select",
        "admin_config_gateway_status_push_mode_label",
        "admin_config_gateway_status_push_mode_hint",
        options=("guest", "main"),
    ),
    ConfigFieldSpec(
        "gateway_status_push_office_url",
        ("gateway", "status", "push", "officeUrl"),
        "text",
        "admin_config_gateway_status_push_office_url_label",
        "admin_config_gateway_status_push_office_url_hint",
        placeholder="https://office.example.com",
    ),
    ConfigFieldSpec(
        "gateway_status_push_join_key",
        ("gateway", "status", "push", "joinKey"),
        "text",
        "admin_config_gateway_status_push_join_key_label",
    ),
    ConfigFieldSpec(
        "gateway_status_push_agent_name",
        ("gateway", "status", "push", "agentName"),
        "text",
        "admin_config_gateway_status_push_agent_name_label",
        placeholder="hahobot",
    ),
    ConfigFieldSpec(
        "gateway_status_push_timeout",
        ("gateway", "status", "push", "timeout"),
        "float",
        "admin_config_gateway_status_push_timeout_label",
    ),
    ConfigFieldSpec(
        "channels_whatsapp_enabled",
        ("channels", "whatsapp", "enabled"),
        "bool",
        "admin_config_channels_whatsapp_enabled_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_whatsapp_bridge_url",
        ("channels", "whatsapp", "bridgeUrl"),
        "text",
        "admin_config_channels_whatsapp_bridge_url_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_whatsapp_bridge_token",
        ("channels", "whatsapp", "bridgeToken"),
        "text",
        "admin_config_channels_whatsapp_bridge_token_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_telegram_enabled",
        ("channels", "telegram", "enabled"),
        "bool",
        "admin_config_channels_telegram_enabled_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_telegram_token",
        ("channels", "telegram", "token"),
        "text",
        "admin_config_channels_telegram_token_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_telegram_proxy",
        ("channels", "telegram", "proxy"),
        "text",
        "admin_config_channels_telegram_proxy_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_telegram_stream_edit_interval",
        ("channels", "telegram", "streamEditInterval"),
        "float",
        "admin_config_channels_telegram_stream_edit_interval_label",
        placeholder="0.6",
    ),
    ConfigFieldSpec(
        "channels_discord_enabled",
        ("channels", "discord", "enabled"),
        "bool",
        "admin_config_channels_discord_enabled_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_discord_token",
        ("channels", "discord", "token"),
        "text",
        "admin_config_channels_discord_token_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_discord_gateway_url",
        ("channels", "discord", "gatewayUrl"),
        "text",
        "admin_config_channels_discord_gateway_url_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_discord_intents",
        ("channels", "discord", "intents"),
        "int",
        "admin_config_channels_discord_intents_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_discord_proxy",
        ("channels", "discord", "proxy"),
        "text",
        "admin_config_channels_discord_proxy_label",
        placeholder="socks5://127.0.0.1:1080",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_discord_proxy_username",
        ("channels", "discord", "proxyUsername"),
        "text",
        "admin_config_channels_discord_proxy_username_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_discord_proxy_password",
        ("channels", "discord", "proxyPassword"),
        "text",
        "admin_config_channels_discord_proxy_password_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_discord_streaming",
        ("channels", "discord", "streaming"),
        "bool",
        "admin_config_channels_discord_streaming_label",
    ),
    ConfigFieldSpec(
        "channels_discord_read_receipt_emoji",
        ("channels", "discord", "readReceiptEmoji"),
        "text",
        "admin_config_channels_discord_read_receipt_emoji_label",
        placeholder="👀",
    ),
    ConfigFieldSpec(
        "channels_discord_working_emoji",
        ("channels", "discord", "workingEmoji"),
        "text",
        "admin_config_channels_discord_working_emoji_label",
        placeholder="🔧",
    ),
    ConfigFieldSpec(
        "channels_discord_working_emoji_delay",
        ("channels", "discord", "workingEmojiDelay"),
        "float",
        "admin_config_channels_discord_working_emoji_delay_label",
        placeholder="2.0",
    ),
    ConfigFieldSpec(
        "channels_feishu_enabled",
        ("channels", "feishu", "enabled"),
        "bool",
        "admin_config_channels_feishu_enabled_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_feishu_app_id",
        ("channels", "feishu", "appId"),
        "text",
        "admin_config_channels_feishu_app_id_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_feishu_app_secret",
        ("channels", "feishu", "appSecret"),
        "text",
        "admin_config_channels_feishu_app_secret_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_feishu_encrypt_key",
        ("channels", "feishu", "encryptKey"),
        "text",
        "admin_config_channels_feishu_encrypt_key_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_feishu_verification_token",
        ("channels", "feishu", "verificationToken"),
        "text",
        "admin_config_channels_feishu_verification_token_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_dingtalk_enabled",
        ("channels", "dingtalk", "enabled"),
        "bool",
        "admin_config_channels_dingtalk_enabled_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_dingtalk_client_id",
        ("channels", "dingtalk", "clientId"),
        "text",
        "admin_config_channels_dingtalk_client_id_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_dingtalk_client_secret",
        ("channels", "dingtalk", "clientSecret"),
        "text",
        "admin_config_channels_dingtalk_client_secret_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_slack_enabled",
        ("channels", "slack", "enabled"),
        "bool",
        "admin_config_channels_slack_enabled_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_slack_bot_token",
        ("channels", "slack", "botToken"),
        "text",
        "admin_config_channels_slack_bot_token_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_slack_app_token",
        ("channels", "slack", "appToken"),
        "text",
        "admin_config_channels_slack_app_token_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_qq_enabled",
        ("channels", "qq", "enabled"),
        "bool",
        "admin_config_channels_qq_enabled_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_qq_app_id",
        ("channels", "qq", "appId"),
        "text",
        "admin_config_channels_qq_app_id_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_qq_secret",
        ("channels", "qq", "secret"),
        "text",
        "admin_config_channels_qq_secret_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_matrix_enabled",
        ("channels", "matrix", "enabled"),
        "bool",
        "admin_config_channels_matrix_enabled_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_matrix_homeserver",
        ("channels", "matrix", "homeserver"),
        "text",
        "admin_config_channels_matrix_homeserver_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_matrix_access_token",
        ("channels", "matrix", "accessToken"),
        "text",
        "admin_config_channels_matrix_access_token_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_matrix_user_id",
        ("channels", "matrix", "userId"),
        "text",
        "admin_config_channels_matrix_user_id_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_matrix_device_id",
        ("channels", "matrix", "deviceId"),
        "text",
        "admin_config_channels_matrix_device_id_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_weixin_enabled",
        ("channels", "weixin", "enabled"),
        "bool",
        "admin_config_channels_weixin_enabled_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_weixin_allow_from",
        ("channels", "weixin", "allowFrom"),
        "csv",
        "admin_config_channels_weixin_allow_from_label",
        "admin_config_channels_weixin_allow_from_hint",
        placeholder="*",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_weixin_token",
        ("channels", "weixin", "token"),
        "text",
        "admin_config_channels_weixin_token_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_weixin_route_tag",
        ("channels", "weixin", "routeTag"),
        "text",
        "admin_config_channels_weixin_route_tag_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_weixin_state_dir",
        ("channels", "weixin", "stateDir"),
        "text",
        "admin_config_channels_weixin_state_dir_label",
        placeholder="~/.hahobot/weixin",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_weixin_poll_timeout",
        ("channels", "weixin", "pollTimeout"),
        "int",
        "admin_config_channels_weixin_poll_timeout_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_wecom_enabled",
        ("channels", "wecom", "enabled"),
        "bool",
        "admin_config_channels_wecom_enabled_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_wecom_bot_id",
        ("channels", "wecom", "botId"),
        "text",
        "admin_config_channels_wecom_bot_id_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "channels_wecom_secret",
        ("channels", "wecom", "secret"),
        "text",
        "admin_config_channels_wecom_secret_label",
        restart_required=True,
    ),
    ConfigFieldSpec(
        "tools_restrict_to_workspace",
        ("tools", "restrictToWorkspace"),
        "bool",
        "admin_config_tools_restrict_to_workspace_label",
    ),
    ConfigFieldSpec(
        "tools_web_proxy",
        ("tools", "web", "proxy"),
        "text",
        "admin_config_web_proxy_label",
        placeholder="socks5://127.0.0.1:1080",
    ),
    ConfigFieldSpec(
        "tools_web_search_provider",
        ("tools", "web", "search", "provider"),
        "select",
        "admin_config_web_search_provider_label",
        options=("brave", "searxng", "duckduckgo"),
    ),
    ConfigFieldSpec(
        "tools_web_search_api_key",
        ("tools", "web", "search", "apiKey"),
        "text",
        "admin_config_web_search_api_key_label",
    ),
    ConfigFieldSpec(
        "tools_web_search_base_url",
        ("tools", "web", "search", "baseUrl"),
        "text",
        "admin_config_web_search_base_url_label",
        "admin_config_web_search_base_url_hint",
        placeholder="http://localhost:8080",
    ),
    ConfigFieldSpec(
        "tools_web_search_max_results",
        ("tools", "web", "search", "maxResults"),
        "int",
        "admin_config_web_search_max_results_label",
    ),
    ConfigFieldSpec(
        "tools_exec_enable",
        ("tools", "exec", "enable"),
        "bool",
        "admin_config_exec_enable_label",
    ),
    ConfigFieldSpec(
        "tools_exec_timeout",
        ("tools", "exec", "timeout"),
        "int",
        "admin_config_exec_timeout_label",
    ),
    ConfigFieldSpec(
        "tools_exec_path_append",
        ("tools", "exec", "pathAppend"),
        "text",
        "admin_config_exec_path_append_label",
        "admin_config_exec_path_append_hint",
        placeholder="/usr/local/bin:/usr/sbin",
    ),
    ConfigFieldSpec(
        "tools_exec_allowed_env_keys",
        ("tools", "exec", "allowedEnvKeys"),
        "csv",
        "admin_config_exec_allowed_env_keys_label",
        "admin_config_exec_allowed_env_keys_hint",
        placeholder="JAVA_HOME, GOPATH",
    ),
    ConfigFieldSpec(
        "tools_exec_sandbox",
        ("tools", "exec", "sandbox"),
        "text",
        "admin_config_exec_sandbox_label",
        "admin_config_exec_sandbox_hint",
        placeholder="bwrap",
    ),
    ConfigFieldSpec(
        "tools_image_gen_enabled",
        ("tools", "imageGen", "enabled"),
        "bool",
        "admin_config_image_enabled_label",
    ),
    ConfigFieldSpec(
        "tools_image_gen_api_key",
        ("tools", "imageGen", "apiKey"),
        "text",
        "admin_config_image_api_key_label",
    ),
    ConfigFieldSpec(
        "tools_image_gen_base_url",
        ("tools", "imageGen", "baseUrl"),
        "text",
        "admin_config_image_base_url_label",
        placeholder="https://api.openai.com/v1",
    ),
    ConfigFieldSpec(
        "tools_image_gen_model",
        ("tools", "imageGen", "model"),
        "text",
        "admin_config_image_model_label",
        placeholder="gpt-image-1",
    ),
    ConfigFieldSpec(
        "tools_image_gen_proxy",
        ("tools", "imageGen", "proxy"),
        "text",
        "admin_config_image_proxy_label",
        placeholder="http://127.0.0.1:7890",
    ),
    ConfigFieldSpec(
        "tools_image_gen_timeout",
        ("tools", "imageGen", "timeout"),
        "int",
        "admin_config_image_timeout_label",
    ),
    ConfigFieldSpec(
        "tools_image_gen_reference_image",
        ("tools", "imageGen", "referenceImage"),
        "text",
        "admin_config_image_reference_image_label",
        placeholder="__default__",
    ),
    ConfigFieldSpec(
        "memory_user_backend",
        ("memory", "user", "backend"),
        "select",
        "admin_config_memory_backend_label",
        "admin_config_memory_backend_tooltip",
        options=("sqlite", "file"),
    ),
    ConfigFieldSpec(
        "memory_user_sqlite_top_k",
        ("memory", "user", "sqlite", "topK"),
        "int",
        "admin_config_memory_sqlite_top_k_label",
        "admin_config_memory_sqlite_top_k_tooltip",
    ),
    ConfigFieldSpec(
        "memory_user_sqlite_max_context_chars",
        ("memory", "user", "sqlite", "maxContextChars"),
        "int",
        "admin_config_memory_sqlite_max_context_chars_label",
        "admin_config_memory_sqlite_max_context_chars_tooltip",
    ),
    ConfigFieldSpec(
        "memory_user_sqlite_max_fragment_chars",
        ("memory", "user", "sqlite", "maxFragmentChars"),
        "int",
        "admin_config_memory_sqlite_max_fragment_chars_label",
        "admin_config_memory_sqlite_max_fragment_chars_tooltip",
    ),
    ConfigFieldSpec(
        "tools_mcp_memorix_enabled",
        (),
        "bool",
        "admin_config_memorix_enabled_label",
    ),
    ConfigFieldSpec(
        "tools_mcp_memorix_type",
        ("tools", "mcpServers", "memorix", "type"),
        "select",
        "admin_config_memorix_type_label",
        options=("", "stdio", "streamableHttp", "sse"),
    ),
    ConfigFieldSpec(
        "tools_mcp_memorix_command",
        ("tools", "mcpServers", "memorix", "command"),
        "text",
        "admin_config_memorix_command_label",
        "admin_config_memorix_command_hint",
        placeholder="memorix",
    ),
    ConfigFieldSpec(
        "tools_mcp_memorix_args",
        ("tools", "mcpServers", "memorix", "args"),
        "csv",
        "admin_config_memorix_args_label",
        "admin_config_memorix_args_hint",
        placeholder="serve",
    ),
    ConfigFieldSpec(
        "tools_mcp_memorix_url",
        ("tools", "mcpServers", "memorix", "url"),
        "text",
        "admin_config_memorix_url_label",
        "admin_config_memorix_url_hint",
        placeholder="http://127.0.0.1:3211/mcp",
    ),
    ConfigFieldSpec(
        "tools_mcp_memorix_tool_timeout",
        ("tools", "mcpServers", "memorix", "toolTimeout"),
        "int",
        "admin_config_memorix_tool_timeout_label",
    ),
    ConfigFieldSpec(
        "channels_send_progress",
        ("channels", "sendProgress"),
        "bool",
        "admin_config_channel_send_progress_label",
    ),
    ConfigFieldSpec(
        "channels_send_tool_hints",
        ("channels", "sendToolHints"),
        "bool",
        "admin_config_channel_send_tool_hints_label",
    ),
    ConfigFieldSpec(
        "channels_send_max_retries",
        ("channels", "sendMaxRetries"),
        "int",
        "admin_config_channel_send_max_retries_label",
    ),
    ConfigFieldSpec(
        "channels_transcription_provider",
        ("channels", "transcriptionProvider"),
        "select",
        "admin_config_channel_transcription_provider_label",
        options=("groq", "openai"),
    ),
    ConfigFieldSpec(
        "channels_transcription_language",
        ("channels", "transcriptionLanguage"),
        "text",
        "admin_config_channel_transcription_language_label",
        "admin_config_channel_transcription_language_hint",
        placeholder="zh",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_enabled",
        ("channels", "voiceReply", "enabled"),
        "bool",
        "admin_config_voice_enabled_label",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_channels",
        ("channels", "voiceReply", "channels"),
        "csv",
        "admin_config_voice_channels_label",
        "admin_config_voice_channels_hint",
        placeholder="telegram, qq",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_provider",
        ("channels", "voiceReply", "provider"),
        "select",
        "admin_config_voice_provider_label",
        options=("openai", "edge", "sovits"),
    ),
    ConfigFieldSpec(
        "channels_voice_reply_model",
        ("channels", "voiceReply", "model"),
        "text",
        "admin_config_voice_model_label",
        placeholder="gpt-4o-mini-tts",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_voice",
        ("channels", "voiceReply", "voice"),
        "text",
        "admin_config_voice_voice_label",
        placeholder="alloy",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_instructions",
        ("channels", "voiceReply", "instructions"),
        "textarea",
        "admin_config_voice_instructions_label",
        rows=5,
    ),
    ConfigFieldSpec(
        "channels_voice_reply_speed",
        ("channels", "voiceReply", "speed"),
        "float",
        "admin_config_voice_speed_label",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_response_format",
        ("channels", "voiceReply", "responseFormat"),
        "select",
        "admin_config_voice_response_format_label",
        options=("mp3", "opus", "aac", "flac", "wav", "pcm", "silk"),
    ),
    ConfigFieldSpec(
        "channels_voice_reply_api_key",
        ("channels", "voiceReply", "apiKey"),
        "text",
        "admin_config_voice_api_key_label",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_api_base",
        ("channels", "voiceReply", "apiBase"),
        "text",
        "admin_config_voice_api_base_label",
        "admin_config_voice_api_base_hint",
        placeholder="https://api.openai.com/v1",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_edge_voice",
        ("channels", "voiceReply", "edgeVoice"),
        "text",
        "admin_config_edge_voice_label",
        placeholder="zh-CN-XiaoxiaoNeural",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_edge_rate",
        ("channels", "voiceReply", "edgeRate"),
        "text",
        "admin_config_edge_rate_label",
        placeholder="+0%",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_edge_volume",
        ("channels", "voiceReply", "edgeVolume"),
        "text",
        "admin_config_edge_volume_label",
        placeholder="+0%",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_sovits_api_url",
        ("channels", "voiceReply", "sovitsApiUrl"),
        "text",
        "admin_config_sovits_api_url_label",
        placeholder="http://127.0.0.1:9880",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_sovits_refer_wav_path",
        ("channels", "voiceReply", "sovitsReferWavPath"),
        "text",
        "admin_config_sovits_refer_wav_path_label",
        placeholder="workspace/personas/Aria/reference.wav",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_sovits_prompt_text",
        ("channels", "voiceReply", "sovitsPromptText"),
        "textarea",
        "admin_config_sovits_prompt_text_label",
        rows=4,
    ),
    ConfigFieldSpec(
        "channels_voice_reply_sovits_prompt_language",
        ("channels", "voiceReply", "sovitsPromptLanguage"),
        "text",
        "admin_config_sovits_prompt_language_label",
        placeholder="zh",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_sovits_text_language",
        ("channels", "voiceReply", "sovitsTextLanguage"),
        "text",
        "admin_config_sovits_text_language_label",
        placeholder="zh",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_sovits_cut_punc",
        ("channels", "voiceReply", "sovitsCutPunc"),
        "text",
        "admin_config_sovits_cut_punc_label",
        placeholder="，。",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_sovits_top_k",
        ("channels", "voiceReply", "sovitsTopK"),
        "int",
        "admin_config_sovits_top_k_label",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_sovits_top_p",
        ("channels", "voiceReply", "sovitsTopP"),
        "float",
        "admin_config_sovits_top_p_label",
    ),
    ConfigFieldSpec(
        "channels_voice_reply_sovits_temperature",
        ("channels", "voiceReply", "sovitsTemperature"),
        "float",
        "admin_config_sovits_temperature_label",
    ),
)
_CONFIG_FIELD_MAP = {field.name: field for field in _CONFIG_FIELDS}
_BLANK_AS_NONE_FIELDS = {
    "tools_web_proxy",
    "tools_image_gen_proxy",
    "tools_mcp_memorix_type",
    "channels_telegram_proxy",
    "channels_discord_proxy",
    "channels_discord_proxy_username",
    "channels_discord_proxy_password",
    "channels_voice_reply_speed",
}
_MEMORIX_CONFIG_FIELD_NAMES = {
    "tools_mcp_memorix_enabled",
    "tools_mcp_memorix_type",
    "tools_mcp_memorix_command",
    "tools_mcp_memorix_args",
    "tools_mcp_memorix_url",
    "tools_mcp_memorix_tool_timeout",
}
_PROVIDER_POOL_CONFIG_FIELD_NAMES = {
    "agents_defaults_provider_pool_strategy",
    "agents_defaults_provider_pool_targets",
}
_PROVIDER_CONFIG_GROUPS = (
    (
        "openrouter",
        "admin_provider_group_openrouter_title",
        "admin_provider_group_openrouter_desc",
        (
            "providers_openrouter_api_key",
            "providers_openrouter_api_base",
        ),
    ),
    (
        "openai",
        "admin_provider_group_openai_title",
        "admin_provider_group_openai_desc",
        (
            "providers_openai_api_key",
            "providers_openai_api_base",
        ),
    ),
    (
        "anthropic",
        "admin_provider_group_anthropic_title",
        "admin_provider_group_anthropic_desc",
        (
            "providers_anthropic_api_key",
            "providers_anthropic_api_base",
        ),
    ),
    (
        "deepseek",
        "admin_provider_group_deepseek_title",
        "admin_provider_group_deepseek_desc",
        (
            "providers_deepseek_api_key",
            "providers_deepseek_api_base",
        ),
    ),
    (
        "custom",
        "admin_provider_group_custom_title",
        "admin_provider_group_custom_desc",
        (
            "providers_custom_api_key",
            "providers_custom_api_base",
            "providers_custom_extra_headers",
        ),
    ),
    (
        "ollama",
        "admin_provider_group_ollama_title",
        "admin_provider_group_ollama_desc",
        ("providers_ollama_api_base",),
    ),
    (
        "vllm",
        "admin_provider_group_vllm_title",
        "admin_provider_group_vllm_desc",
        ("providers_vllm_api_base",),
    ),
)
_CHANNEL_CONFIG_GROUPS = (
    (
        "whatsapp",
        "admin_channel_group_whatsapp_title",
        "admin_channel_group_whatsapp_desc",
        (
            "channels_whatsapp_enabled",
            "channels_whatsapp_bridge_url",
            "channels_whatsapp_bridge_token",
        ),
    ),
    (
        "telegram",
        "admin_channel_group_telegram_title",
        "admin_channel_group_telegram_desc",
        (
            "channels_telegram_enabled",
            "channels_telegram_token",
            "channels_telegram_proxy",
            "channels_telegram_stream_edit_interval",
        ),
    ),
    (
        "discord",
        "admin_channel_group_discord_title",
        "admin_channel_group_discord_desc",
        (
            "channels_discord_enabled",
            "channels_discord_token",
            "channels_discord_gateway_url",
            "channels_discord_intents",
            "channels_discord_proxy",
            "channels_discord_proxy_username",
            "channels_discord_proxy_password",
            "channels_discord_streaming",
            "channels_discord_read_receipt_emoji",
            "channels_discord_working_emoji",
            "channels_discord_working_emoji_delay",
        ),
    ),
    (
        "feishu",
        "admin_channel_group_feishu_title",
        "admin_channel_group_feishu_desc",
        (
            "channels_feishu_enabled",
            "channels_feishu_app_id",
            "channels_feishu_app_secret",
            "channels_feishu_encrypt_key",
            "channels_feishu_verification_token",
        ),
    ),
    (
        "dingtalk",
        "admin_channel_group_dingtalk_title",
        "admin_channel_group_dingtalk_desc",
        (
            "channels_dingtalk_enabled",
            "channels_dingtalk_client_id",
            "channels_dingtalk_client_secret",
        ),
    ),
    (
        "slack",
        "admin_channel_group_slack_title",
        "admin_channel_group_slack_desc",
        (
            "channels_slack_enabled",
            "channels_slack_bot_token",
            "channels_slack_app_token",
        ),
    ),
    (
        "qq",
        "admin_channel_group_qq_title",
        "admin_channel_group_qq_desc",
        (
            "channels_qq_enabled",
            "channels_qq_app_id",
            "channels_qq_secret",
        ),
    ),
    (
        "matrix",
        "admin_channel_group_matrix_title",
        "admin_channel_group_matrix_desc",
        (
            "channels_matrix_enabled",
            "channels_matrix_homeserver",
            "channels_matrix_access_token",
            "channels_matrix_user_id",
            "channels_matrix_device_id",
        ),
    ),
    (
        "weixin",
        "admin_channel_group_weixin_title",
        "admin_channel_group_weixin_desc",
        (
            "channels_weixin_enabled",
            "channels_weixin_allow_from",
            "channels_weixin_token",
            "channels_weixin_route_tag",
            "channels_weixin_state_dir",
            "channels_weixin_poll_timeout",
        ),
    ),
    (
        "wecom",
        "admin_channel_group_wecom_title",
        "admin_channel_group_wecom_desc",
        (
            "channels_wecom_enabled",
            "channels_wecom_bot_id",
            "channels_wecom_secret",
        ),
    ),
)
_CHANNEL_CONFIG_SECTION_FIELDS = tuple(
    field_name for _, _, _, field_names in _CHANNEL_CONFIG_GROUPS for field_name in field_names
)
_CHANNEL_CONFIG_FIELD_NAMES = set(_CHANNEL_CONFIG_SECTION_FIELDS)
_CHANNEL_CONFIG_FIELD_TO_GROUP = {
    field_name: group_key
    for group_key, _, _, field_names in _CHANNEL_CONFIG_GROUPS
    for field_name in field_names
}
_CHANNEL_GROUP_SUMMARY_URL_FIELDS = {
    "channels_whatsapp_bridge_url",
    "channels_telegram_proxy",
    "channels_discord_gateway_url",
    "channels_discord_proxy",
    "channels_matrix_homeserver",
}
_CONFIG_SECTIONS = (
    (
        "admin_config_section_agents_title",
        "admin_config_section_agents_desc",
        (
            "agents_defaults_workspace",
            "agents_defaults_model",
            "agents_defaults_provider",
            "agents_defaults_provider_pool_strategy",
            "agents_defaults_provider_pool_targets",
            "agents_defaults_max_tokens",
            "agents_defaults_context_window_tokens",
            "agents_defaults_temperature",
            "agents_defaults_max_tool_iterations",
            "agents_defaults_tool_hint_max_length",
            "agents_defaults_reasoning_effort",
            "agents_defaults_timezone",
        ),
    ),
    (
        "admin_config_section_providers_title",
        "admin_config_section_providers_desc",
        (
            "providers_openrouter_api_key",
            "providers_openrouter_api_base",
            "providers_openai_api_key",
            "providers_openai_api_base",
            "providers_anthropic_api_key",
            "providers_anthropic_api_base",
            "providers_deepseek_api_key",
            "providers_deepseek_api_base",
            "providers_custom_api_key",
            "providers_custom_api_base",
            "providers_custom_extra_headers",
            "providers_ollama_api_base",
            "providers_vllm_api_base",
        ),
    ),
    (
        "admin_config_section_gateway_title",
        "admin_config_section_gateway_desc",
        (
            "gateway_host",
            "gateway_port",
            "gateway_heartbeat_enabled",
            "gateway_heartbeat_interval_s",
            "gateway_heartbeat_keep_recent_messages",
            "gateway_cron_max_sleep_ms",
            "gateway_admin_enabled",
            "gateway_admin_auth_key",
            "gateway_status_enabled",
            "gateway_status_auth_key",
        ),
    ),
    (
        "admin_config_section_status_push_title",
        "admin_config_section_status_push_desc",
        (
            "gateway_status_push_enabled",
            "gateway_status_push_mode",
            "gateway_status_push_office_url",
            "gateway_status_push_join_key",
            "gateway_status_push_agent_name",
            "gateway_status_push_timeout",
        ),
    ),
    (
        "admin_config_section_channels_title",
        "admin_config_section_channels_desc",
        _CHANNEL_CONFIG_SECTION_FIELDS,
    ),
    (
        "admin_config_section_web_title",
        "admin_config_section_web_desc",
        (
            "tools_restrict_to_workspace",
            "tools_web_proxy",
            "tools_web_search_provider",
            "tools_web_search_api_key",
            "tools_web_search_base_url",
            "tools_web_search_max_results",
        ),
    ),
    (
        "admin_config_section_exec_title",
        "admin_config_section_exec_desc",
        (
            "tools_exec_enable",
            "tools_exec_timeout",
            "tools_exec_path_append",
            "tools_exec_allowed_env_keys",
            "tools_exec_sandbox",
        ),
    ),
    (
        "admin_config_section_image_title",
        "admin_config_section_image_desc",
        (
            "tools_image_gen_enabled",
            "tools_image_gen_api_key",
            "tools_image_gen_base_url",
            "tools_image_gen_model",
            "tools_image_gen_proxy",
            "tools_image_gen_timeout",
            "tools_image_gen_reference_image",
        ),
    ),
    (
        "admin_config_section_memory_title",
        "admin_config_section_memory_desc",
        (
            "memory_user_backend",
            "memory_user_sqlite_top_k",
            "memory_user_sqlite_max_context_chars",
            "memory_user_sqlite_max_fragment_chars",
        ),
    ),
    (
        "admin_config_section_memorix_title",
        "admin_config_section_memorix_desc",
        (
            "tools_mcp_memorix_enabled",
            "tools_mcp_memorix_type",
            "tools_mcp_memorix_command",
            "tools_mcp_memorix_args",
            "tools_mcp_memorix_url",
            "tools_mcp_memorix_tool_timeout",
        ),
    ),
    (
        "admin_config_section_channel_runtime_title",
        "admin_config_section_channel_runtime_desc",
        (
            "channels_send_progress",
            "channels_send_tool_hints",
            "channels_send_max_retries",
            "channels_transcription_provider",
            "channels_transcription_language",
        ),
    ),
    (
        "admin_config_section_voice_title",
        "admin_config_section_voice_desc",
        (
            "channels_voice_reply_enabled",
            "channels_voice_reply_channels",
            "channels_voice_reply_provider",
            "channels_voice_reply_model",
            "channels_voice_reply_voice",
            "channels_voice_reply_instructions",
            "channels_voice_reply_speed",
            "channels_voice_reply_response_format",
            "channels_voice_reply_api_key",
            "channels_voice_reply_api_base",
        ),
    ),
    (
        "admin_config_section_edge_title",
        "admin_config_section_edge_desc",
        (
            "channels_voice_reply_edge_voice",
            "channels_voice_reply_edge_rate",
            "channels_voice_reply_edge_volume",
        ),
    ),
    (
        "admin_config_section_sovits_title",
        "admin_config_section_sovits_desc",
        (
            "channels_voice_reply_sovits_api_url",
            "channels_voice_reply_sovits_refer_wav_path",
            "channels_voice_reply_sovits_prompt_text",
            "channels_voice_reply_sovits_prompt_language",
            "channels_voice_reply_sovits_text_language",
            "channels_voice_reply_sovits_cut_punc",
            "channels_voice_reply_sovits_top_k",
            "channels_voice_reply_sovits_top_p",
            "channels_voice_reply_sovits_temperature",
        ),
    ),
)
